// <auto-generated />
using System;
using ABPGroup.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ABPGroup.Migrations
{
    [DbContext(typeof(ABPGroupDbContext))]
    [Migration("20260320164000_AddIsPublicToCodeGenSessions")]
    partial class AddIsPublicToCodeGenSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ABPGroup.CodeGen.CodeGenSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompletedStepsJson")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmedStackJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPhase")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DetectedEntitiesJson")
                        .HasColumnType("text");

                    b.Property<string>("DetectedFeaturesJson")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GeneratedFilesJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GenerationCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GenerationStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedRequirement")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Prompt")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("RepairAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("ScaffoldTemplate")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("SpecConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ValidationResultsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CodeGenSessions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}